name: Xteve Docker Image Publish

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  Xteve docker image publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
     
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to AliYun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_TOKEN }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        context: .
        push: true
        tags: |
          clion007/xteve:latest
          registry.cn-chengdu.aliyuncs.com/clion/xteve:latest
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
